# Generated by Django 4.2.1 on 2023-06-05 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
