# Generated by Django 4.2.1 on 2023-06-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(max_length=255, upload_to='')),
                ('date', models.DateField(auto_now_add=True)),
                ('blog', models.TextField(max_length=5000)),
            ],
        ),
    ]
